Repository Block-Equity/stellar-android-wallet, pull requests merged in 2018-11, with the labels that each got.

#69 disabling rtl support
  app/src/androidTest/java/blockeq/com/stellarwallet/ApplicationEspressoTest.kt
  app/src/main/AndroidManifest.xml
Labels: bug, ready for review

#71 Patching the random generator with a high entropy
  app/src/main/java/blockeq/com/stellarwallet/WalletApplication.kt
  app/src/main/java/blockeq/com/stellarwallet/encryption/PRNGFixes.java
Labels: enhancement, ready for review

#104 #103_request_pin_when_changing_security_settings
  app/src/main/java/blockeq/com/stellarwallet/activities/PinActivity.kt
  app/src/main/java/blockeq/com/stellarwallet/fragments/SettingsFragment.kt
  app/src/main/java/blockeq/com/stellarwallet/models/PinViewState.kt
Labels: bug

#125 Add asset
  app/lint.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/blockeq/stellarwallet/activities/AddAssetActivity.kt
  app/src/main/java/com/blockeq/stellarwallet/activities/AssetsActivity.kt
  app/src/main/java/com/blockeq/stellarwallet/activities/DiagnosticActivity.kt
  app/src/main/java/com/blockeq/stellarwallet/adapters/AssetsRecyclerViewAdapter.kt
  app/src/main/java/com/blockeq/stellarwallet/fragments/SettingsFragment.kt
  app/src/main/java/com/blockeq/stellarwallet/helpers/Constants.kt
  app/src/main/res/drawable/bg_rounded_button_blue.xml
  app/src/main/res/drawable/bg_rounded_button_grey.xml
  app/src/main/res/layout/activity_add_asset.xml
  app/src/main/res/layout/activity_inflation.xml
  app/src/main/res/layout/activity_view_secret_seed.xml
  app/src/main/res/layout/content_assets_activity.xml
  app/src/main/res/layout/content_enter_address.xml
  app/src/main/res/layout/content_receive.xml
  app/src/main/res/layout/item_asset.xml
  app/src/main/res/values/strings.xml
Labels: feature

#129 Diagnostic Tool for Android - v2.1
  app/src/main/java/com/blockeq/stellarwallet/activities/AssetsActivity.kt
  app/src/main/java/com/blockeq/stellarwallet/activities/DiagnosticActivity.kt
  app/src/main/java/com/blockeq/stellarwallet/activities/EnterAddressActivity.kt
  app/src/main/java/com/blockeq/stellarwallet/activities/MnemonicActivity.kt
  app/src/main/java/com/blockeq/stellarwallet/activities/PinActivity.kt
  app/src/main/java/com/blockeq/stellarwallet/activities/RecoverWalletActivity.kt
  app/src/main/java/com/blockeq/stellarwallet/helpers/Constants.kt
  app/src/main/java/com/blockeq/stellarwallet/models/Diagnostic.kt
  app/src/main/java/com/blockeq/stellarwallet/models/Fields.kt
  app/src/main/java/com/blockeq/stellarwallet/utils/AccountUtils.kt
  app/src/main/res/layout/activity_diagnostic.xml
  app/src/main/res/values/strings.xml
Labels: feature
